apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-sample-data
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
          path: "/home/ubuntu/jenkins/sqlserver"
