apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-sample-data
  labels:
    app: sqlserver
    tier: database
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
          path: "/home/ubuntu/jenkins/sqlserver"
